name: Terraform Workflow

on:
  push:
    branches:
      - '**' # Triggers for all branches

  pull_request:
    branches:
      - main
permissions:
  id-token: write
  
jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Change to Terraform Directory
        run: cd terraform_102

      - name: Terraform Init
        id: init-step
        run: 
         cd ./terraform_102 && terraform init

      - name: Upload Terraform Folder
        uses: actions/upload-artifact@v3
        with:
          name: terraform-init
          path: ./**/

  validate:
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: removed existing terraform files
        run: |
          rm -r ./**
          ls -la

      - name: Download Terraform Folder
        uses: actions/download-artifact@v3
        with:
          name: terraform-init

      - name: Terraform init
        run: 
          cd ./terraform_102 && terraform init

      - name: Terraform Validate
        run: 
          terraform validate

  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: removed existing terraform files
        run: |
          rm -r ./**
          ls -la

      - name: Download Terraform Folder
        uses: actions/download-artifact@v3
        with:
          name: terraform-init

      - name: Terraform init
        run: 
          cd ./terraform_102 && terraform init

      - name: Terraform validate
        run: 
          cd ./terraform_102 && terraform validate 

      - name: Terraform plan
        run: 
           cd ./terraform_101 && terraform plan

    

 
          